# Generated by Django 3.2.5 on 2021-07-08 10:14

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='unknown.png', upload_to=shop.models.get_img_upload_path, verbose_name='product image'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_warehouse',
            field=models.BooleanField(default=False, verbose_name='on warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='sold'),
        ),
    ]
